version: '3'
services:
  yii2-app:
    build:
      dockerfile: Dockerfile
      context: 'php'
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    depends_on:
      - mysql
    ports:
      - "2080:9880"
      - "2081:9881"
    volumes:
      # Application testing
      - ./app:/app:delegated
      # Composer cache
      - ./.composer-docker/cache:/root/.composer/cache:delegated
  mysql:
    image: mysql:5.7
    #restart: always
    container_name: "yii2-mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=iapl
      - MYSQL_PASSWORD=iapl
      - MYSQL_ROOT_PASSWORD=iapl
      - MYSQL_DATABASE=iapl
    ports:
      - "33060:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
