version: '3'
services:

  yii2-app:
    build:
      dockerfile: Dockerfile
      context: 'php'
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    depends_on:
      - postgresql
    ports:
      - "2080:80"
      - "2081:81"
    volumes:
      # Application testing
      - ./app:/app:delegated
      # Composer cache
      - ./.composer-docker/cache:/root/.composer/cache:delegated
  postgresql:
    image: postgres:12
    restart: always
    container_name: "yii2-postgresql"
    environment:
      - POSTGRES_USER=iapl
      - POSTGRES_PASSWORD=iapl
      - POSTGRES_DB=iapl
    ports:
      - "54320:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
